version: "3.9"
services:
  my-rabbit:
    build: ./.docker/rabbitmq/
    container_name: rabbitmq
    hostname: rabbit-mapper-host
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./docker/rabbitmq/data:/var/lib/rabbitmq"
      - "./docker/rabbitmq/log:/var/log/rabbitmq"
      - "./.docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
