version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbimq-mapper
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672