export type DIMENSION_TYPE = [width: number, height: number, depth: number]

const DIMENSION_DEFAULT: DIMENSION_TYPE = [1, 1, 1]

export const QUEUE_DIMENSION: DIMENSION_TYPE = DIMENSION_DEFAULT
export const EXCHANGE_DIMENSION: DIMENSION_TYPE = DIMENSION_DEFAULT
export const CONSUMER_DIMENSION: DIMENSION_TYPE = DIMENSION_DEFAULT
export const PRODUCER_DIMENSION: DIMENSION_TYPE = DIMENSION_DEFAULT

export const NUMBER_POINTS: number = 100;